apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: htwnjxcr3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/htwnjxcr3-java-quarkus-gitops